language: csharp
solution: Duplicati.sln
dotnet: 2.0.0
install:
  - nuget restore Duplicati.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
  - sudo pip install selenium
  - if [ ! -d ~/build/duplicati/duplicati/packages/SharpCompress.0.18.2 ]; then ln -s ~/build/duplicati/duplicati/packages/sharpcompress.0.18.2 ~/build/duplicati/duplicati/packages/SharpCompress.0.18.2; fi
addons:
  coverity_scan:
    project:
      name: "duplicati/duplicati"
      description: "Duplicati Build submitted via Travis CI"
    notification_email: kenneth@duplicati.com
    build_command_prepend: "msbuild /t:Clean"
    build_command:   "msbuild /t:Rebuild"
    branch_pattern: coverity_scan
env:
  global:
    # The next declaration is the encrypted COVERITY_SCAN_TOKEN, created
    #   via the "travis encrypt" command using the project repo's public key
    - secure: "ijaQDcVcMo/utuP514FiDZVGR5LJbATWmYDmgRIIaI0YG2Rk6uuJp9XXDXr8sx66JWttPGgs7Htqfy50VKHdr7nsfyCQCRNGmqF+OJeUgAQMj5spxn9A7PZY9+GVhnXoJ06wvYjCv5MPeLBMDK/KpIM5Ny5IG+TKzQy4U7Dyg0riMUT61aqzxSjTGfHZPmaqBICJTzsRmeGHglemFUz/1B4NAN+IeAtXoH9YIfA2LjJfYmMLckPgFQLKN/tQRaGPWXh77y0qVgA++K8UVu5W3yGo3JXBPDdabGgKs9BPlfN5/Ixnkcy6ekAubDA/Aspur9x7/szj4/AnGMY6frNB33nQcnJQZ/51GYKr6CXCmjoJQuWc8ZKdEMqDn3w/kyEzvluSjAsJNRVboeWPE4VfpAeUBsjQ+TuEQi8WXhN8VJgZV7yCkVlZTVbhtOxMPsBiFb74lpWC2iQuWLJv9ED6vyXZVzZhNtfjXNXNZzIwYxbcd7I0ZQ8fmDstFnvBJveJby2ZRpECXTbc03eIUq1SAaVJJY2r47RD1PwVqM3xvUTljIqtKdyIz915mEOjqG1BnCDaiGHYJ4byuDDeIUZO9X70s60Gh4hupZA2Ruup0v7SfYgkto6aNcStd0NYd716Vd7hqXNTp6nu01L5YYJDY4h5sHyBXVXbxCKlUb01kUw="
  general:
    - USAGEREPORTER_Duplicati_LEVEL=none
    - AUTOUPDATER_Duplicati_SKIP_UPDATE=1
    - TMPDIR=$HOME/tmp

jobs:
  include:
    - stage: Run unittests
      env: CATEGORY=Border
    - env: CATEGORY=Filter

    - env: CATEGORY=BulkNormal
      cache:
        directories:
          - $HOME/download/bulk

    - env: CATEGORY=BulkNoSize
      cache:
        directories:
          - $HOME/download/bulk

    - env: CATEGORY=SVNData
      cache:
        directories:
          - $HOME/download/bulk

    - env: CATEGORY=SVNDataLong
      cache:
        directories:
          - $HOME/download/svn

    - env: CATEGORY=Targeted
    - env: CATEGORY=Purge

    - env: CATEGORY=GUI
      addons:
        sauce_connect:
          username: $SAUCE_USERNAME
          access_key: $SAUCE_ACCESS_KEY

before_install:
      - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-

script:
# build duplicati
  - ls -la ~/build/duplicati/duplicati/packages/
  - echo "travis_fold:start:build_duplicati"
  - msbuild /p:Configuration=Release Duplicati.sln
  - echo "travis_fold:end:build_duplicati"
  - cp -r ./Duplicati/Server/webroot ./Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release/webroot
# download and extract testdata
  - echo "travis_fold:start:download_extract_testdata"
  - ls -la .
  - if [ ! -d ~/tmp ]; then mkdir ~/tmp; fi
  - if [ ! -d ~/download ]; then mkdir ~/download; fi
  - if [ ! -d ~/download/svn ]; then mkdir ~/download/svn; fi
  - if [ ! -d ~/download/bulk ]; then mkdir ~/download/bulk; fi
  - if [ ! -f ~/download/svn/DSMCBE.zip ] && ([ "$CATEGORY" == "SVNData" ] || [ "$CATEGORY" == "SVNDataLong" ]); then wget --progress=dot:giga "https://s3.amazonaws.com/duplicati-test-file-hosting/DSMCBE.zip" -O ~/download/svn/DSMCBE.zip; fi
  - if [ ! -f ~/download/bulk/data.zip ] && ([ "$CATEGORY" == "BulkNormal" ] || [ "$CATEGORY" == "BulkNoSize" ]);  then wget --progress=dot:giga "https://s3.amazonaws.com/duplicati-test-file-hosting/data.zip" -O ~/download/bulk/data.zip; fi
  - ls -la .
  - mkdir ~/testdata
  - mkdir ~/testdata/data
  - mkdir ~/testdata/DSMCBE
  - if [ "$CATEGORY" == "SVNData" ] || [ "$CATEGORY" == "SVNDataLong" ]; then unzip -q ~/download/svn/DSMCBE.zip -d ~/testdata/; fi
  - if [ "$CATEGORY" == "BulkNormal" ] || [ "$CATEGORY" == "BulkNoSize" ]; then unzip -q ~/download/bulk/data.zip -d ~/testdata/; fi
  - chown -R travis ~/testdata/
  - chmod -R 755 ~/testdata
  - ls -la ~/testdata
  - ls -la ~/testdata/DSMCBE
  - ls -la ~/testdata/data
  - echo "travis_fold:end:download_extract_testdata"
# run unit tests
  - echo "travis_fold:start:unit_test"
  - if [[ "$CATEGORY" != "GUI" ]]; then mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit3-console.exe ./Duplicati/UnitTest/bin/Release/Duplicati.UnitTest.dll --where:cat==$CATEGORY --workers=1; fi
  - echo "travis_fold:end:unit_test"
# start server and run gui tests
  - echo "travis_fold:start:gui_unit_test"
  - mono ./Duplicati/GUI/Duplicati.GUI.TrayIcon/bin/Release/Duplicati.Server.exe &
  - if [[ "$CATEGORY" == "GUI" ]]; then python guiTests/guiTest.py; fi
  - echo "travis_fold:end:gui_unit_test"
  
